// src/components/record/info/csq/Consequence.vue
<script lang="ts">
import { computed, defineComponent, PropType, toRef } from "vue";
import { FieldMetadata } from "../../../../api/vcf/MetadataParser";
import { Metadata as RecordMetadata, Record } from "../../../../api/vcf/Vcf";
import Anchor from "../../../Anchor.vue";

export default defineComponent({
  name: "VipRecordInfoCsqConsequence",
  components: { Anchor },
  props: {
    field: {
      type: [Array, Boolean, Number, String] as PropType<unknown>,
    },
    fieldMetadata: {
      type: Object as () => FieldMetadata,
      required: true,
    },
    record: {
      type: Object as () => Record,
      required: true,
    },
    recordMetadata: {
      type: Object as () => RecordMetadata,
      required: true,
    },
  },
  setup(props) {
    const field = toRef(props, "field");
    const fieldTyped = computed(() => field.value as string[] | null | undefined);
    return { fieldTyped };
  },
});
</script>

<template>
  <template v-if="fieldTyped">
    <template v-for="(item, index) in fieldTyped" :key="index">
      <span v-if="index !== 0">, </span>
      <Anchor
        :href="`http://www.sequenceontology.org/browser/obob.cgi?rm=term_list&obo_query=${encodeURIComponent(
          item
        )}&release=current_release`"
        :value="item"
      />
    </template>
  </template>
</template>

// src/components/record/info/Consequence.tsx
import { Component, For } from "solid-js";
import { Anchor } from "../../Anchor";

export const Consequence: Component<{
  terms: string[];
}> = (props) => {
  const toHref = (term: string) =>
    `http://www.sequenceontology.org/browser/obob.cgi?rm=term_list&obo_query=${encodeURIComponent(
      term
    )}&release=current_release`;

  return (
    <>
      <For each={props.terms}>
        {(value, i) => (
          <>
            {i() !== 0 && <span>, </span>}
            <Anchor href={toHref(value)} value={value} />
          </>
        )}
      </For>
    </>
  );
};
