// src/components/Gene.vue
<template>
  <span>
    <Anchor
      :href="'https://www.omim.org/search?search=' + encodeURIComponent(value.symbol) + '&field=approved_gene_symbol'"
      :text="value.symbol"
    />
    <b-button
      pill
      v-if="value.incompletePenetrance"
      size="sm"
      variant="info"
      class="ml-2 p-0"
      v-b-tooltip.click
      :title="$t('incompletePenetrance')"
    >
      <sup>IP</sup>
    </b-button>
  </span>
</template>

<script lang="ts">
import Vue, { PropType } from 'vue';
import Anchor from '@/components/Anchor.vue';
import { Gene } from '@/types/Gene';

export default Vue.extend({
  components: { Anchor },
  props: {
    value: { type: Object as PropType<Gene> }
  }
});
</script>

// src/components/record/info/Gene.tsx
import { Component } from "solid-js";
import { Anchor } from "../../Anchor";

export const Gene: Component<{
  symbol: string;
}> = (props) => {
  const toHref = (symbol: string) =>
    `https://www.genenames.org/tools/search/#!/?query=${symbol}&filter=document_type:%22gene%22`;

  return <Anchor href={toHref(props.symbol)} value={props.symbol} />;
};
