// src/components/Anchor.tsx
import { ParentComponent, Show } from "solid-js";

export const Anchor: ParentComponent<{
  href: string | null | undefined;
}> = (props) => {
  return (
    <Show when={props.href} fallback={props.children}>
      {(href) => (
        <a href={href} target="_blank" rel="noopener noreferrer nofollow">
          {props.children}
        </a>
      )}
    </Show>
  );
};

// src/components/Anchor.vue
<template>
  <a :href="href" target="_blank" rel="noopener noreferrer nofollow">
    {{ text }}
  </a>
</template>

<script lang="ts">
import Vue, { PropType } from 'vue';

export default Vue.extend({
  props: {
    href: String as PropType<string>,
    text: [String, Number, Boolean] as PropType<string | number | boolean>
  }
});
</script>
