// src/components/form/Checkbox.vue
<script lang="ts">
import { computed, defineComponent } from "vue";

export default defineComponent({
  name: "VCheckbox",
  props: {
    modelValue: {
      type: [String, Array as () => string[]],
      required: true,
    },
    value: {
      type: String,
      required: true,
    },
  },
  emits: ["change", "update:modelValue"],
  setup(props, { emit }) {
    const computedValue = computed({
      get: () => props.modelValue,
      set: (newValue) => emit("update:modelValue", newValue),
    });

    const handleChange = (event: Event) => emit("change", { value: (event.target as HTMLInputElement).checked });

    return {
      computedValue,
      handleChange,
    };
  },
});
</script>

<template>
  <label class="checkbox">
    <input v-model="computedValue" type="checkbox" :value="value" @change="handleChange" />
    <slot />
  </label>
</template>

// src/components/Checkbox.tsx
import { Component, createSignal } from "solid-js";

export type CheckboxEvent = {
  value: string;
  checked: boolean;
};

export const Checkbox: Component<{
  value: string | undefined;
  label: string;
  onChange: (event: CheckboxEvent) => void;
}> = (props) => {
  const [checked, setChecked] = createSignal(false);

  const onChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    setChecked(target.checked);
    props.onChange({
      value: target.value,
      checked: target.checked,
    });
  };

  return (
    <label class="checkbox">
      <input class="mr-1" type="checkbox" value={props.value} checked={checked()} onChange={onChange} />
      {props.label}
    </label>
  );
};
