// src/components/GenomeBrowser.tsx
import { Component, onCleanup, onMount } from "solid-js";
import igv from "igv";
import api from "../Api";
import { fromByteArray } from "base64-js";
import { writeVcf } from "@molgenis/vip-report-vcf/src/VcfWriter";
import { ComposedQuery, Sample } from "@molgenis/vip-report-api/src/Api";

async function createVcf(contig: string, position: number, samples: Sample[]): Promise<Uint8Array> {
  const query: ComposedQuery = {
    operator: "and",
    args: [
      { selector: "c", operator: "==", args: contig },
      {
        operator: "and",
        args: [
          { selector: "p", operator: ">=", args: position - 250 },
          { selector: "p", operator: "<=", args: position + 250 },
        ],
      },
    ],
  };
  const data = await Promise.all([api.getRecordsMeta(), api.getRecords({ query, size: Number.MAX_SAFE_INTEGER })]);
  const vcf = writeVcf(
    { metadata: data[0], data: data[1].items.map((item) => item.data) },
    { samples: samples.map((sample) => sample.person.individualId) }
  );
  return toBytes(vcf);
}

const toBytes = (str: string): Uint8Array => Uint8Array.from(str.split("").map((letter) => letter.charCodeAt(0)));

const createBrowserConfig = async (contig: string, position: number, samples: Sample[]): Promise<unknown | null> => {
  const data = await Promise.all([
    api.getFastaGz(contig, position),
    createVcf(contig, position, samples),
    api.getGenesGz(),
    ...samples.map((sample) => api.getBam(sample.person.individualId)),
  ]);
  const fastaGz = data[0];
  const vcf = data[1];
  const genesGz = data[2];
  const bams = data.slice(3);

  if (fastaGz === null) {
    return null;
  }
  let order = 1;
  const tracks = [];
  if (genesGz) {
    tracks.push({
      order: order++,
      type: "annotation",
      format: "refGene",
      name: "Genes",
      url: "data:application/gzip;base64," + fromByteArray(genesGz),
    });
  }
  tracks.push({
    order: order++,
    type: "variant",
    format: "vcf",
    name: "Variants",
    url: "data:application/octet-stream;base64," + fromByteArray(vcf),
  });

  for (let i = 0; i < samples.length; ++i) {
    const bam = bams[i];

    if (bam !== null) {
      const sampleId = samples[i].person.individualId;
      tracks.push({
        order: order++,
        type: "alignment",
        format: "bam",
        name: `Alignment (${sampleId})`,
        url: "data:application/gzip;base64," + fromByteArray(bam),
      });
    }
  }

  const htsFileMetadata = await api.getHtsFileMetadata();

  return {
    reference: {
      id: htsFileMetadata.genomeAssembly,
      name: "Reference",
      fastaURL: "data:application/gzip;base64," + fromByteArray(fastaGz),
      tracks: tracks,
    },
    locus: `${contig}:${position}`,
    showChromosomeWidget: false,
    loadDefaultGenomes: false,
    showCenterGuide: true,
  };
};

export const GenomeBrowser: Component<{ contig: string; position: number; samples: Sample[] }> = (props) => {
  let div: HTMLDivElement;
  let browser: unknown;
  onMount(() => {
    (async () => {
      const config = await createBrowserConfig(props.contig, props.position, props.samples);
      if (config !== null) {
        browser = await igv.createBrowser(div, config);
      }
    })().catch((err) => console.error(err));
  });
  onCleanup(() => {
    if (browser) {
      igv.removeBrowser(browser);
    }
  });
  return <div ref={div} />;
};

// src/components/GenomeBrowser.vue
<template>
  <div ref="igv"></div>
</template>

<script lang="ts">
import Vue from 'vue';
import igv from 'igv';
import { mapActions, mapGetters, mapState } from 'vuex';
import { Vcf } from '@molgenis/vip-report-api';

export default Vue.extend({
  computed: {
    ...mapGetters(['genomeBrowserDb']),
    ...mapState(['selectedRecord', 'selectedSample'])
  },
  methods: {
    ...mapActions(['getBam', 'getFastaGz', 'getGenesGz', 'getVcfGz']),
    hasGenomeBrowser() {
      return Vue.prototype.$browser !== undefined;
    },
    async createGenomeBrowser(config: unknown) {
      Vue.prototype.$browser = await igv.createBrowser(this.$refs.igv, config);
    },
    async updateGenomeBrowser(record: Vcf.Record | null) {
      const config = record !== null ? await this.createBrowserConfig(record) : null;
      if (config === null) {
        if (this.hasGenomeBrowser()) {
          await this.deleteGenomeBrowser();
        }
      } else {
        if (this.hasGenomeBrowser()) {
          Vue.prototype.$browser.loadSessionObject(config);
        } else {
          await this.createGenomeBrowser(config);
        }
      }
    },
    async deleteGenomeBrowser() {
      igv.removeBrowser(Vue.prototype.$browser);
      Vue.prototype.$browser = undefined;
    },
    async createBrowserConfig(record: Vcf.Record): Promise<unknown | null> {
      const sampleIds = [];
      if (this.selectedSample) {
        const sampleId = this.selectedSample.person.individualId;
        sampleIds.push(sampleId);

        const paternalId = this.selectedSample.person.paternalId;
        if (paternalId !== '0') {
          sampleIds.push(paternalId);
        }

        const maternalId = this.selectedSample.person.maternalId;
        if (maternalId !== '0') {
          sampleIds.push(maternalId);
        }
      }

      const data = await Promise.all([
        this.getFastaGz({ contig: record.c, pos: record.p }),
        this.getVcfGz(),
        this.getGenesGz(),
        ...sampleIds.map((sampleId) => this.getBam(sampleId))
      ]);
      const fastaGz = data[0];
      const vcfGz = data[1];
      const genesGz = data[2];
      const bams = data.slice(3);
      if (fastaGz === null) {
        return null;
      }

      let order = 1;
      let tracks = [];
      if (genesGz) {
        tracks.push({
          order: order++,
          type: 'annotation',
          format: 'refGene',
          name: 'Genes',
          url: 'data:application/gzip;base64,' + genesGz.toString('base64')
        });
      }
      tracks.push({
        order: order++,
        type: 'variant',
        format: 'vcf',
        name: 'Variants',
        url: 'data:application/gzip;base64,' + vcfGz.toString('base64')
      });

      for (let i = 0; i < sampleIds.length; ++i) {
        const bam = bams[i];
        if (bam !== null) {
          const sampleId = sampleIds[i];
          tracks.push({
            order: order++,
            type: 'alignment',
            format: 'bam',
            name: `Alignment (${sampleId})`,
            url: 'data:application/gzip;base64,' + bam.toString('base64')
          });
        }
      }

      return {
        reference: {
          id: this.genomeBrowserDb !== null ? this.genomeBrowserDb : 'reference_unknown',
          name: this.genomeBrowserDb !== null ? this.genomeBrowserDb : 'Reference',
          fastaURL: 'data:application/gzip;base64,' + fastaGz.toString('base64'),
          tracks: tracks
        },
        locus: record.c + ':' + record.p,
        showChromosomeWidget: false,
        loadDefaultGenomes: false,
        nucleotideColors: {
          A: 'rgb(144, 238, 144)',
          C: 'rgb(176, 196, 222)',
          T: 'rgb(238, 162, 173)',
          G: 'rgb(255, 236, 139)',
          N: 'rgb(80,80,80)'
        },
        showCenterGuide: true
      };
    }
  },
  watch: {
    selectedRecord(newRecord: Vcf.Record | null) {
      this.updateGenomeBrowser(newRecord);
    }
  }
});
</script>
