// src/components/SearchBox.vue
<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  name: "VipSearchBox",
  emits: ["search-change"],
  setup(props, context) {
    const inputValue = ref("");
    const onInput = () => context.emit("search-change", inputValue.value);

    const onInputClear = () => {
      inputValue.value = "";
      context.emit("search-change", inputValue.value);
    };
    return { inputValue, onInput, onInputClear };
  },
});
</script>

<template>
  <div class="field has-addons">
    <p class="control has-icons-right is-expanded">
      <input v-model="inputValue" class="input" type="text" @keyup.enter="onInput" @keyup.esc="onInputClear" />
      <span v-if="inputValue.length > 0" class="icon is-clickable is-small is-right" @click="onInputClear">
        <font-awesome-icon icon="circle-xmark" />
      </span>
    </p>
    <div class="control">
      <a class="button is-info" @click="onInput">
        <span class="icon is-small is-left">
          <font-awesome-icon icon="search" />
        </span>
      </a>
    </div>
  </div>
</template>

// src/components/SearchBox.tsx
import { Component, createSignal } from "solid-js";

export const SearchBox: Component<{ onInput: (value: string) => void }> = (props) => {
  const [value, setValue] = createSignal("");

  return (
    <div class="field has-addons">
      <p class="control has-icons-right is-expanded">
        <input
          class="input"
          type="text"
          value={value()}
          onInput={(e) => setValue((e.target as HTMLInputElement).value)}
          onKeyUp={(e) => {
            if (e.code === "Enter") {
              props.onInput(value());
            } else if (e.code === "Escape") {
              setValue("");
              props.onInput("");
            }
          }}
        />
        {value().length > 0 && (
          <span
            class="icon is-clickable is-right"
            onClick={() => {
              setValue("");
              props.onInput("");
            }}
          >
            <i class="fa-solid fa-circle-xmark" />
          </span>
        )}
      </p>
      <div class="control">
        <a class="button is-info" onClick={() => props.onInput(value())}>
          <span class="icon is-left">
            <i class="fa-solid fa-search" />
          </span>
        </a>
      </div>
    </div>
  );
};
