// src/components/Filters.tsx
import { Component, For } from "solid-js";
import { FieldMetadataContainer } from "../api/vcf/VcfParser";
import { FieldMetadata } from "../api/vcf/MetadataParser";
import { Filter } from "./Filter";
import { flattenFieldMetadata } from "../utils/field";

export type FilterChangeEvent = {
  fieldMetadata: FieldMetadata;
  value: string[];
};

export type FilterClearEvent = {
  fieldMetadata: FieldMetadata;
};

export type FiltersChangeEvent = {
  filters: FilterChangeEvent[];
};

type Filters = {
  [key: string]: FilterChangeEvent;
};

export const Filters: Component<{
  fieldMetadataContainer: FieldMetadataContainer;
  onChange: (event: FiltersChangeEvent) => void;
}> = (props) => {
  const infoMetadataItems = flattenFieldMetadata(props.fieldMetadataContainer).filter(
    (fieldMetadata) => fieldMetadata.type === "CATEGORICAL"
  );
  const filters: Filters = {};

  const onFilterChange = (event: FilterChangeEvent) => {
    filters[event.fieldMetadata.id] = event;
    props.onChange({ filters: Object.values(filters) });
  };
  const onFilterClear = (event: FilterClearEvent) => {
    delete filters[event.fieldMetadata.id];
    props.onChange({ filters: Object.values(filters) });
  };

  return (
    <>
      <For each={infoMetadataItems}>
        {(infoMetadata) => <Filter fieldMetadata={infoMetadata} onChange={onFilterChange} onClear={onFilterClear} />}
      </For>
    </>
  );
};

// src/components/record/filter/Filters.vue
<script lang="ts">
import { computed, defineComponent, Ref, ref, toRef } from "vue";
import { FieldMetadataContainer } from "../../../api/vcf/VcfParser";
import Filter from "./Filter.vue";
import { flattenFieldMetadata, getId } from "../../../utils/field";
import { FilterChangeEvent, FilterClearEvent } from "../../../utils/filter";

export default defineComponent({
  name: "VipRecordFilters",
  components: { Filter },
  props: {
    infoMetadataContainer: {
      type: Object as () => FieldMetadataContainer,
      required: true,
    },
  },
  emits: ["filters-change"],
  setup(props, context) {
    const filters: Ref<{ [key: string]: FilterChangeEvent }> = ref({});

    const infoMetadataContainer = toRef(props, "infoMetadataContainer");
    const infoMetadataItems = computed(() => flattenFieldMetadata(infoMetadataContainer.value));

    const onFiltersChange = () => context.emit("filters-change", { filters: Object.values(filters.value) });

    const onFilterChange = (event: FilterChangeEvent) => {
      filters.value[getId(event.fieldMetadata)] = event;
      onFiltersChange();
    };
    const onFilterClear = (event: FilterClearEvent) => {
      delete filters.value[getId(event.fieldMetadata)];
      onFiltersChange();
    };

    return { infoMetadataItems, onFilterChange, onFilterClear };
  },
});
</script>

<template>
  <Filter
    v-for="(infoMetadata, index) in infoMetadataItems"
    :key="index"
    :field-metadata="infoMetadata"
    @filter-change="onFilterChange"
    @filter-clear="onFilterClear"
  />
</template>
